// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/6/2025, 6:17:26 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/rlong/Sandbox/aetherlink/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/plugins/**/*.{js,ts,mjs}","/home/rlong/Sandbox/aetherlink/composables/**/*.{js,ts,mjs}","/home/rlong/Sandbox/aetherlink/utils/**/*.{js,ts,mjs}","/home/rlong/Sandbox/aetherlink/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/rlong/Sandbox/aetherlink/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;