"""
MAC OUI (Organizationally Unique Identifier) to Vendor mapping
Comprehensive database for device identification
"""

MAC_VENDORS = {
    # Apple (extensive list)
    "00:03:93": {"vendor": "Apple", "type": "phone"},
    "00:0a:95": {"vendor": "Apple", "type": "laptop"},
    "00:17:f2": {"vendor": "Apple", "type": "laptop"},
    "00:1b:63": {"vendor": "Apple", "type": "laptop"},
    "00:1f:5b": {"vendor": "Apple", "type": "laptop"},
    "00:23:df": {"vendor": "Apple", "type": "laptop"},
    "00:25:00": {"vendor": "Apple", "type": "laptop"},
    "00:26:08": {"vendor": "Apple", "type": "laptop"},
    "04:0c:ce": {"vendor": "Apple", "type": "phone"},
    "04:d3:cf": {"vendor": "Apple", "type": "phone"},
    "08:66:98": {"vendor": "Apple", "type": "phone"},
    "0c:74:c2": {"vendor": "Apple", "type": "phone"},
    "10:93:e9": {"vendor": "Apple", "type": "phone"},
    "14:bd:61": {"vendor": "Apple", "type": "phone"},
    "18:34:51": {"vendor": "Apple", "type": "phone"},
    "1c:ab:a7": {"vendor": "Apple", "type": "phone"},
    "20:c9:d0": {"vendor": "Apple", "type": "phone"},
    "24:a2:e1": {"vendor": "Apple", "type": "phone"},
    "28:cf:e9": {"vendor": "Apple", "type": "phone"},
    "2c:be:08": {"vendor": "Apple", "type": "phone"},
    "30:90:ab": {"vendor": "Apple", "type": "phone"},
    "34:36:3b": {"vendor": "Apple", "type": "phone"},
    "38:c9:86": {"vendor": "Apple", "type": "phone"},
    "3c:15:c2": {"vendor": "Apple", "type": "phone"},
    "40:30:04": {"vendor": "Apple", "type": "phone"},
    "40:a6:d9": {"vendor": "Apple", "type": "phone"},
    "44:00:10": {"vendor": "Apple", "type": "phone"},
    "48:60:bc": {"vendor": "Apple", "type": "phone"},
    "4c:57:ca": {"vendor": "Apple", "type": "phone"},
    "50:ea:d6": {"vendor": "Apple", "type": "phone"},
    "54:26:96": {"vendor": "Apple", "type": "phone"},
    "54:ea:a8": {"vendor": "Apple", "type": "phone"},
    "58:55:ca": {"vendor": "Apple", "type": "phone"},
    "5c:59:48": {"vendor": "Apple", "type": "phone"},
    "60:33:4b": {"vendor": "Apple", "type": "phone"},
    "60:f8:1d": {"vendor": "Apple", "type": "phone"},
    "64:20:0c": {"vendor": "Apple", "type": "phone"},
    "64:a3:cb": {"vendor": "Apple", "type": "phone"},
    "68:5b:35": {"vendor": "Apple", "type": "phone"},
    "68:a8:6d": {"vendor": "Apple", "type": "phone"},
    "6c:19:c0": {"vendor": "Apple", "type": "phone"},
    "6c:96:cf": {"vendor": "Apple", "type": "phone"},
    "70:48:0f": {"vendor": "Apple", "type": "phone"},
    "74:e2:f5": {"vendor": "Apple", "type": "phone"},
    "78:31:c1": {"vendor": "Apple", "type": "phone"},
    "78:ca:39": {"vendor": "Apple", "type": "phone"},
    "7c:04:d0": {"vendor": "Apple", "type": "phone"},
    "7c:6d:f8": {"vendor": "Apple", "type": "phone"},
    "80:49:71": {"vendor": "Apple", "type": "phone"},
    "80:e6:50": {"vendor": "Apple", "type": "phone"},
    "84:38:35": {"vendor": "Apple", "type": "phone"},
    "88:53:95": {"vendor": "Apple", "type": "phone"},
    "8c:00:6d": {"vendor": "Apple", "type": "phone"},
    "8c:29:37": {"vendor": "Apple", "type": "phone"},
    "90:72:40": {"vendor": "Apple", "type": "phone"},
    "94:e9:6a": {"vendor": "Apple", "type": "phone"},
    "98:01:a7": {"vendor": "Apple", "type": "phone"},
    "9c:04:eb": {"vendor": "Apple", "type": "phone"},
    "a0:99:9b": {"vendor": "Apple", "type": "phone"},
    "a4:31:35": {"vendor": "Apple", "type": "phone"},
    "a4:5e:60": {"vendor": "Apple", "type": "phone"},
    "a4:83:e7": {"vendor": "Apple", "type": "phone"},
    "a8:20:66": {"vendor": "Apple", "type": "phone"},
    "a8:5b:78": {"vendor": "Apple", "type": "phone"},
    "a8:66:7f": {"vendor": "Apple", "type": "phone"},
    "ac:1f:74": {"vendor": "Apple", "type": "phone"},
    "ac:87:a3": {"vendor": "Apple", "type": "phone"},
    "b0:34:95": {"vendor": "Apple", "type": "phone"},
    "b4:18:d1": {"vendor": "Apple", "type": "phone"},
    "b8:09:8a": {"vendor": "Apple", "type": "phone"},
    "b8:41:a4": {"vendor": "Apple", "type": "phone"},
    "b8:53:ac": {"vendor": "Apple", "type": "phone"},
    "bc:3b:af": {"vendor": "Apple", "type": "phone"},
    "bc:52:b7": {"vendor": "Apple", "type": "phone"},
    "c0:1a:da": {"vendor": "Apple", "type": "phone"},
    "c0:63:94": {"vendor": "Apple", "type": "phone"},
    "c4:2c:03": {"vendor": "Apple", "type": "phone"},
    "c8:2a:14": {"vendor": "Apple", "type": "phone"},
    "c8:69:cd": {"vendor": "Apple", "type": "phone"},
    "cc:08:8d": {"vendor": "Apple", "type": "phone"},
    "cc:29:f5": {"vendor": "Apple", "type": "phone"},
    "d0:03:4b": {"vendor": "Apple", "type": "phone"},
    "d0:25:98": {"vendor": "Apple", "type": "phone"},
    "d4:9a:20": {"vendor": "Apple", "type": "phone"},
    "d8:1c:79": {"vendor": "Apple", "type": "phone"},
    "d8:30:62": {"vendor": "Apple", "type": "phone"},
    "dc:2b:2a": {"vendor": "Apple", "type": "phone"},
    "dc:56:e7": {"vendor": "Apple", "type": "phone"},
    "e0:5f:45": {"vendor": "Apple", "type": "phone"},
    "e0:ac:cb": {"vendor": "Apple", "type": "phone"},
    "e4:25:e7": {"vendor": "Apple", "type": "phone"},
    "e8:04:0b": {"vendor": "Apple", "type": "phone"},
    "e8:80:2e": {"vendor": "Apple", "type": "phone"},
    "f0:24:75": {"vendor": "Apple", "type": "phone"},
    "f0:99:b6": {"vendor": "Apple", "type": "phone"},
    "f0:db:e2": {"vendor": "Apple", "type": "phone"},
    "f4:0f:24": {"vendor": "Apple", "type": "phone"},
    "f8:27:93": {"vendor": "Apple", "type": "phone"},
    "fc:25:3f": {"vendor": "Apple", "type": "phone"},
    # Amazon
    "00:71:47": {"vendor": "Amazon", "type": "speaker"},
    "00:fc:8b": {"vendor": "Amazon", "type": "tv"},
    "04:d3:b0": {"vendor": "Amazon", "type": "speaker"},
    "18:74:2e": {"vendor": "Amazon", "type": "speaker"},
    "34:d2:70": {"vendor": "Amazon", "type": "speaker"},
    "38:f7:3d": {"vendor": "Amazon", "type": "speaker"},
    "44:65:0d": {"vendor": "Amazon", "type": "speaker"},
    "4c:ef:c0": {"vendor": "Amazon", "type": "speaker"},
    "50:dc:e7": {"vendor": "Amazon", "type": "speaker"},
    "68:37:e9": {"vendor": "Amazon", "type": "speaker"},
    "68:54:fd": {"vendor": "Amazon", "type": "speaker"},
    "74:75:48": {"vendor": "Amazon", "type": "speaker"},
    "74:c2:46": {"vendor": "Amazon", "type": "speaker"},
    "84:d6:d0": {"vendor": "Amazon", "type": "speaker"},
    "a0:02:dc": {"vendor": "Amazon", "type": "tv"},
    "ac:63:be": {"vendor": "Amazon", "type": "speaker"},
    "b0:7d:64": {"vendor": "Amazon", "type": "speaker"},
    "cc:f4:11": {"vendor": "Amazon", "type": "speaker"},
    "dc:31:18": {"vendor": "Amazon", "type": "speaker"},
    "f0:27:2d": {"vendor": "Amazon", "type": "speaker"},
    "fc:a6:67": {"vendor": "Amazon", "type": "speaker"},
    "fc:65:de": {"vendor": "Amazon", "type": "speaker"},
    # Roku
    "b0:a7:37": {"vendor": "Roku", "type": "tv"},
    "d8:31:34": {"vendor": "Roku", "type": "tv"},
    "cc:6d:a0": {"vendor": "Roku", "type": "tv"},
    "ac:3a:7a": {"vendor": "Roku", "type": "tv"},
    "b8:a1:75": {"vendor": "Roku", "type": "tv"},
    # Sony
    "00:1d:ba": {"vendor": "Sony", "type": "tv"},
    "00:23:be": {"vendor": "Sony", "type": "tv"},
    "30:f9:ed": {"vendor": "Sony", "type": "tv"},
    "54:42:49": {"vendor": "Sony", "type": "tv"},
    "ac:9b:0a": {"vendor": "Sony", "type": "tv"},
    "fc:f1:52": {"vendor": "Sony", "type": "tv"},
    # Samsung
    "00:12:fb": {"vendor": "Samsung", "type": "tv"},
    "00:16:32": {"vendor": "Samsung", "type": "tv"},
    "00:1b:98": {"vendor": "Samsung", "type": "phone"},
    "20:64:32": {"vendor": "Samsung", "type": "tv"},
    "40:0e:85": {"vendor": "Samsung", "type": "phone"},
    "54:88:0e": {"vendor": "Samsung", "type": "tv"},
    "7c:64:56": {"vendor": "Samsung", "type": "phone"},
    "e8:50:8b": {"vendor": "Samsung", "type": "tv"},
    # Google/Nest
    "1c:f2:9a": {"vendor": "Google", "type": "speaker"},
    "30:fd:38": {"vendor": "Google", "type": "speaker"},
    "48:d6:d5": {"vendor": "Google", "type": "speaker"},
    "54:60:09": {"vendor": "Google", "type": "speaker"},
    "6c:ad:f8": {"vendor": "Google", "type": "speaker"},
    "a4:77:33": {"vendor": "Google", "type": "speaker"},
    "b4:f6:2a": {"vendor": "Google", "type": "speaker"},
    "d4:f5:47": {"vendor": "Google", "type": "speaker"},
    "f4:f5:d8": {"vendor": "Google", "type": "speaker"},
    # TP-Link
    "50:c7:bf": {"vendor": "TP-Link", "type": "iot"},
    "b0:95:75": {"vendor": "TP-Link", "type": "iot"},
    "c0:06:c3": {"vendor": "TP-Link", "type": "iot"},
    # Netgear
    "20:e5:2a": {"vendor": "Netgear", "type": "router"},
    "2c:30:33": {"vendor": "Netgear", "type": "router"},
    "a0:04:60": {"vendor": "Netgear", "type": "router"},
    # Ring
    "74:c6:3b": {"vendor": "Ring", "type": "iot"},
    "b0:c7:45": {"vendor": "Ring", "type": "iot"},
    # Philips Hue
    "00:17:88": {"vendor": "Philips Hue", "type": "iot"},
    "ec:b5:fa": {"vendor": "Philips Hue", "type": "iot"},
    # Raspberry Pi
    "b8:27:eb": {"vendor": "Raspberry Pi", "type": "iot"},
    "dc:a6:32": {"vendor": "Raspberry Pi", "type": "iot"},
    "e4:5f:01": {"vendor": "Raspberry Pi", "type": "iot"},
    # Microsoft
    "00:50:f2": {"vendor": "Microsoft", "type": "laptop"},
    "ac:22:0b": {"vendor": "Microsoft", "type": "laptop"},
    # Dell
    "00:14:22": {"vendor": "Dell", "type": "laptop"},
    "d0:67:e5": {"vendor": "Dell", "type": "laptop"},
    # HP
    "00:1b:78": {"vendor": "HP", "type": "laptop"},
    "2c:27:d7": {"vendor": "HP", "type": "laptop"},
    # Lenovo
    "00:1f:16": {"vendor": "Lenovo", "type": "laptop"},
    "54:ee:75": {"vendor": "Lenovo", "type": "laptop"},
}
